name: base_product
abstract: true

camera:
  lens:
    preset: 50mm_normal
    aperture: f/5.6

lighting:
  rig: product_hero

backdrop:
  type: infinite_curve
  preset: gray_studio

color:
  look:
    preset: kodak_2383
    intensity: 0.5
